<?php
	
	/**
	 * This file contains the widget class
	 */
	
	if ( !defined( 'devTools' ) )  {
		
		define( 'devTools' , TRUE ) ;  
		
		class devTools {
			
			public function __construct( ) {}
			
			/**
			 * 	getTitle
			 * 
			 * 	Function returns the html string of the tile
			 * 
			 * 	@return	string		The html of the itle 
			 */
			public function getTitle() {
				return '<div class="developer-tool"><H2>DEVELOPER TOOL: WGT</H2>' ;	
			}
			
			/**
			 * 	getManual
			 * 
			 * 	Function returns the Manual table
			 * 
			 * 	@param	$A			The application variable for paths
			 * 
			 * 	@return	string		The html table of the manual
			 */
			public function getManual( $A ) {
				$rtn = '<table class="wgt">
							<tr>
								<th>Argument</th>
								<th>Mandatory</th>
								<th>description</th>
								<th>example</th></tr>
							<tr>
								<th>wgt</th>
								<td>TRUE</td>
								<td>The name of the widget to view</td>
								<td> /?wgt=toolbar-menu</td>
							 </tr>
							 <tr>
								<th>man</th>
								<td></td>
								<td>Brings up the manual</td>
								<td> /?man</td>
							 </tr>
							 <tr>
								<th>css</th>
								<td></td>
								<td>Sets optional css files to use, will take a CSV list.</td>
								<td> /?wgt=toolbar-menu&css=toolbar-menu.css,main.css</td>
							 </tr>
							 <tr>
								<th>cfg</th>
								<td></td>
								<td>Sets an alternate configuration file to use,default is config.php found in the widget.</td>
								<td> /?wgt=toolbar-menu&cfg=config.php</td>
							 </tr>
							 <tr>
								<th>argv</th>
								<td></td>
								<td>Sets optional run time parametrs to use, widget must be set to use them. Will take a comma separated list.</td>
								<td> /?wgt=toolbar-menu&argv=1,2,3,4</td>
							 </tr>
							</table>' ;	
				
				return $rtn ;
			}
		
			/**
			 * 	setParameters
			 * 
			 * 	Function determines and sets the parameters for the 
			 * 	target widget, css files and javascript files should 
			 *  already have been generated by the dev-css.php and and 
			 * 	dev-js.php files
			 * 
			 * 	@return	array		The parameter array
			 */
			public function setParameters() {
				
				// Checking if manual is being generated
				if ( isset( $_GET[ 'man' ] ) ) {
						$WGT[ 'JS' ] = NULL ;
						$WGT[ 'CSS' ] = NULL ;
				}
				
				// producing parameters for a widget
				else {
					//	wgt name	
					if ( isset( $_GET[ 'wgt' ] ) )  {
						$WGT[ 'WGT' ] = $_GET[ 'wgt' ] ;
					}
					else {
						$WGT[ 'WGT' ] = NULL ;
					}
					
					//	css files to use	
					if ( isset( $_GET[ 'css' ] ) )  {
						$WGT[ 'CSS' ] = getCSVArray( $_GET[ 'css' ] ) ;
					}
					else {
						$WGT[ 'CSS' ] = getCSVArray( $_GET[ 'wgt' ].'.css,main.css' ) ;
					}
						
					//	javascript file to use	
					if( isset( $_GET[ 'js' ] ) )  {
						$WGT[ 'JS' ] = getCSVArray( $_GET[ 'js' ] ) ;
					}
					else {
						$WGT[ 'JS' ] = NULL ;
					}
						
					// 	configuration file to use
					if( isset( $_GET[ 'cfg' ] ) )  {
						$WGT[ 'CONFIG' ] = getCSVArray( $_GET[ 'cfg' ] );
					}
					else {
						$WGT[ 'CONFIG' ] = NULL ;
					}
					
					//	widget arguments
					if( isset( $_GET[ 'argv' ] ) ) {
						$WGT[ 'ARGV' ] = $_GET[ 'argv'] ;
					}
					else {
						$WGT[ 'ARGV' ] = NULL ;
					}
					
					return $WGT ;
				}
			}
			
			/**
			 * 	getStats
			 * 
			 * 	this generates a widget stats table
			 * 
			 * 	@param	$A		The application global for path names
			 * 	@param	$WGT	The widget parameter variable
			 * 
			 * 	@return $rtn 	The table to display
			 */	
			public function getStats( $A , $WGT ){
				$rtn =  '<table class="wgt">';
				$rtn .= getDevRow( 'WGT'  , $_GET[ 'wgt' ] ) ;
				$rtn .= getDevRow( 'PATH' , $A[ 'D_WGT' ].$_GET[ 'wgt' ].'\\index.php' ) ;
				$rtn .= getDevRow( 'CSS'  , $WGT[ 'CSS' ] ) ;
				$rtn .= getDevRow( 'JS'   , $WGT[ 'JS' ] ) ;
				$rtn .= getDevRow( 'CFG'  , $WGT[ 'CONFIG' ] ) ;
				$rtn .= getDevRow( 'ARGV' , $WGT[ 'ARGV' ] ) ;
				$rtn .= '</table>' ;
				return $rtn ;
			}
		}
	}
	
	// create an instance of the widget
	
	$WGT[ 'OBJ' ] = new devTools ;
		
?>
